#!/bin/bash

source /etc/envvars

export ROLE=kube-controller-manager
export CN="system:kube-controller-manager"
export TTL=720h
export COMMAND="sv restart controller-manager"

export PKI_DIR=/dev/shm/kubernetes
export VAULT_TOKEN=${KUBE_CONTROLLER_MANAGER_TOKEN:-$(grep "token " $PKI_DIR/KUBE_CONTROLLER_MANAGER_TOKEN | awk '{print $2}')}
rm $PKI_DIR/KUBE_CONTROLLER_MANAGER_TOKEN

exec 2>&1
exec /consul-template.sh
