#!/bin/sh

#sv start socklog-unix || exit 1

ETCD_OPTS="-advertise-client-urls=http://0.0.0.0:4001 -listen-client-urls=http://0.0.0.0:4001 -data-dir=/var/lib/etcd-data"

exec 2>&1
exec etcd ${ETCD_OPTS}
