#!/bin/sh

#sv start socklog-unix || exit 1

IP=`ip route get 1 | awk '{print $NF;exit}'`
ETCD_OPTS="-addr=$IP:4001 -bind-addr=0.0.0.0:4001 -data-dir=/var/lib/etcd-data"

exec 2>&1
exec etcd ${ETCD_OPTS}
