#!/bin/bash

docker rm -f kmaster
docker run \
       -e KUBERNETES_MASTER="$KUBERNETES_MASTER" \
       -e CLOUD_PROVIDER="$CLOUD_PROVIDER" \
       -e AWS_PROFILE="$AWS_PROFILE" \
       -e VPC_ID="$VPC_ID" \
       -e ALT_NAMES="$ALT_NAMES" \
       --name kmaster \
       --net=host \
       -p 4001:4001 \
       -p 8080:8080 \
       -p 8200:8200 \
       -v `pwd`/etcd-data:/var/lib/etcd-data \
       -v `pwd`/vault-data:/var/lib/vault-data \
       -v `pwd`/pki-data:/srv/kubernetes \
       -v /var/log:/var/log \
       -it kubernetes-master bash
