#!/bin/bash

source /etc/envvars

until curl -k -s $KUBERNETES_MASTER; do echo "Waiting for API Server..."; sleep 3; done;

export ROLE=cluster-admin
export CN="cluster-admin"
export TTL=720h
export COMMAND="sv restart addon-manager"

export PKI_DIR=/dev/shm/kubernetes
export VAULT_TOKEN=${ADDON_MANAGER_TOKEN:-$(grep "token " $PKI_DIR/ADDON_MANAGER_TOKEN | awk '{print $2}')}
rm $PKI_DIR/ADDON_MANAGER_TOKEN

exec 2>&1
exec /consul-template.sh
