#!/bin/bash

source /etc/envvars

export ROLE=kubelet
export CN="system:node:$NODE_NAME"
export TTL=720h
export COMMAND="sv restart kubelet"

export PKI_DIR=/dev/shm/kubernetes
export VAULT_TOKEN=$(grep "token " $PKI_DIR/KUBELET_TOKEN | awk '{print $2}')
rm $PKI_DIR/KUBELET_TOKEN

exec 2>&1
exec /consul-template.sh
