#!/bin/bash

sv start etcd || exit 1

source /etc/envvars

KUBE_CONTROLLER_MANAGER_OPTS="\
--master=127.0.0.1:8080 \
--node-monitor-grace-period=20s \
--pod-eviction-timeout=300s \
--logtostderr=true \
--root-ca-file=/srv/kubernetes/ca.crt \
--service-account-private-key-file=/srv/kubernetes/server.key \
"

exec 2>&1
exec kube-controller-manager ${KUBE_CONTROLLER_MANAGER_OPTS}
