#!/bin/bash

source /etc/envvars

until curl -k -s https://localhost:6443; do echo "Waiting for API Server..."; sleep 3; done;

export PKI_DIR=/dev/shm/kubernetes

KUBE_CONTROLLER_MANAGER_OPTS="\
--master=http://localhost:8080 \
--root-ca-file=$PKI_DIR/kubernetes-ca.pem \
--service-account-private-key-file=$PKI_DIR/service-account-key.pem \
--cluster-signing-cert-file=$PKI_DIR/cluster-signing-ca.pem \
--cluster-signing-key-file=$PKI_DIR/cluster-signing-key.pem \
--feature-gates=$FEATURE_GATES \
--terminated-pod-gc-threshold 100 \
--flex-volume-plugin-dir=/var/lib/kubelet/volumeplugins \
--allocate-node-cidrs=true \
--cluster-cidr "$CLUSTER_CIDR" \
--logtostderr=true \
"

exec 2>&1
exec kube-controller-manager ${KUBE_CONTROLLER_MANAGER_OPTS}
