#!/bin/bash

sv start etcd || exit 1

source /etc/envvars

KUBE_APISERVER_OPTS="\
--insecure-bind-address=0.0.0.0 \
--insecure-port=8080 \
--secure-port=443 \
--etcd_servers=http://127.0.0.1:4001 \
--logtostderr=true \
--v=1 \
--service-cluster-ip-range=172.27.0.0/16 \
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,PodPreset \
--allow-privileged=true \
--runtime-config=api/all \
--client-ca-file=/srv/kubernetes/ca.crt \
--tls-cert-file=/srv/kubernetes/server.crt \
--tls-private-key-file=/srv/kubernetes/server.key \
--service-account-key-file=/srv/kubernetes/service-account.key \
--token_auth_file=/srv/kube-apiserver/known_tokens.csv \
--storage-backend=etcd2 \
--storage-media-type=application/json \
--audit-log-path=/var/log/apiserver/audit.log \
"

exec 2>&1
exec kube-apiserver ${KUBE_APISERVER_OPTS}
