#!/bin/bash

sv start apiserver || exit 1
sv start influxdb || exit 1

source /etc/envvars

until curl http://localhost:8080; do echo "waiting for Kubernetes to come online..."; sleep 3; done;

cd /heapster

kubectl --namespace=kube-system delete services heapster
kubectl apply -f heapster-service.yaml

sed -i -e "s|{{ IP }}|$(hostname -I|cut -d' ' -f1)|" heapster-endpoint.yaml
kubectl --namespace=kube-system delete endpoints heapster
kubectl apply -f heapster-endpoint.yaml

exec 2>&1
exec ./heapster --source=kubernetes:http://localhost:8080?inClusterConfig=false --sink=influxdb:http://localhost:8086
