#!/bin/bash

source /etc/envvars

until curl -k -s https://localhost:6443; do echo "Waiting for API Server..."; sleep 3; done;

export PKI_DIR=/dev/shm/kubernetes
export ROLE=kubelet
export USER="system:node:$NODE_NAME"

export IP=`ip route get 1 | awk '{print $7;exit}'`
HOST=`hostname -s`
mkdir -p /etc/kubernetes/manifests

KUBELET_OPTS="\
--hostname_override=$NODE_NAME \
--address=0.0.0.0 \
--cluster_dns=172.27.0.2 \
--cluster-domain=cluster.local \
--port=10250 \
--containerized=false \
--image-gc-high-threshold=50 \
--image-gc-low-threshold=30 \
--registry-qps=0 \
--hairpin-mode=hairpin-veth \
--serialize-image-pulls=false \
--node-labels=host=${HOST},${LABELS} \
--pod-manifest-path=/etc/kubernetes/manifests \
--kube-reserved=cpu=100m,memory=100Mi \
--system-reserved=cpu=100m,memory=100Mi \
--kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml \
--feature-gates=$FEATURE_GATES \
--register-with-taints=$TAINTS \
--volume-plugin-dir=/var/lib/kubelet/volumeplugins \
--anonymous-auth=false \
--authentication-token-webhook=true \
--authorization-mode=Webhook \
--tls-cert-file=$PKI_DIR/$ROLE-cert.pem \
--tls-private-key-file=$PKI_DIR/$ROLE-key.pem \
--client-ca-file=$PKI_DIR/$ROLE-ca.pem \
--logtostderr=true \
--v=2 \
"

mkdir -p $PKI_DIR
kubectl config set-cluster kubernetes \
    --certificate-authority=$PKI_DIR/$ROLE-ca.pem \
    --server=https://$HOSTNAME:6443 \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-credentials $USER \
    --client-certificate=$PKI_DIR/$ROLE-cert.pem \
    --client-key=$PKI_DIR/$ROLE-key.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-context default \
    --cluster=kubernetes \
    --user=$USER \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config use-context default --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml

#setup cgroups
for cgroup in /sys/fs/cgroup/*; do
  if [ -d $cgroup ]; then
    mkdir -p $cgroup/kubepods
  fi
done

exec 2>&1
exec kubelet ${KUBELET_OPTS}
