#!/bin/bash

source /etc/envvars

until curl -k -s $KUBERNETES_MASTER; do echo "Waiting for API Server..."; sleep 3; done;

export PKI_DIR=/dev/shm/kubernetes
export ROLE=addon-manager
export USER="addon-manager"

kubectl config set-cluster local \
    --server=$KUBERNETES_MASTER \
    --certificate-authority=$PKI_DIR/$ROLE-ca.pem
kubectl config set-credentials $USER \
    --client-certificate=$PKI_DIR/$ROLE-cert.pem \
    --client-key=$PKI_DIR/$ROLE-key.pem
kubectl config set-context local \
    --cluster=local \
    --user=$USER
kubectl config use-context local

exec 2>&1
exec /opt/kube-addons.sh
