#!/bin/bash

source /etc/envvars

until curl -s $KUBERNETES_MASTER; do echo "Waiting for API Server..."; sleep 3; done;

KUBE_SCHEDULER_OPTS="\
  --logtostderr=true \
  --master=$KUBERNETES_MASTER \
  --feature-gates=$FEATURE_GATES \
  --policy-config-file=${SCHEDULER_POLICY_FILE} \
  --v=2"

exec 2>&1
exec kube-scheduler ${KUBE_SCHEDULER_OPTS}
