#!/bin/bash

source /etc/envvars

until curl -k -s $KUBERNETES_MASTER; do echo "Waiting for API Server..."; sleep 3; done;

export PKI_DIR=/dev/shm/kubernetes
export ROLE=kube-scheduler
export USER="system:kube-scheduler"

KUBE_SCHEDULER_OPTS="\
--master=$KUBERNETES_MASTER \
--kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml \
--feature-gates=$FEATURE_GATES \
--policy-config-file=${SCHEDULER_POLICY_FILE} \
--v=2"

mkdir -p $PKI_DIR
kubectl config set-cluster kubernetes \
    --server=$KUBERNETES_MASTER \
    --certificate-authority=$PKI_DIR/$ROLE-ca.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-credentials $USER \
    --client-certificate=$PKI_DIR/$ROLE-cert.pem \
    --client-key=$PKI_DIR/$ROLE-key.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-context default \
    --cluster=kubernetes \
    --user=$USER \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config use-context default --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml

exec 2>&1
exec kube-scheduler ${KUBE_SCHEDULER_OPTS}
