#!/bin/bash

sv apiserver etcd || exit 1

source /etc/envvars

until curl 127.0.0.1:8080; do echo "Waiting for API Server..."; sleep 3; done;

KUBE_SCHEDULER_OPTS="\
  --logtostderr=true \
  --master=127.0.0.1:8080 \
  --feature-gates=$FEATURE_GATES \
  --policy-config-file=${SCHEDULER_POLICY_FILE} \
  --v=2"

exec 2>&1
exec kube-scheduler ${KUBE_SCHEDULER_OPTS}
