#!/bin/bash

source /etc/envvars

until curl -s localhost:10255/healthz; do echo "Waiting for Kubelet..."; sleep 5; done

export PKI_DIR=/dev/shm/kubernetes
export ROLE=proxy
export USER=system:kube-proxy

KUBE_PROXY_OPTS="\
--hostname-override=$NODE_NAME \
--cluster-cidr "$CLUSTER_CIDR" \
--proxy-mode=ipvs \
--feature-gates=$FEATURE_GATES \
--kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml \
--v=2 \
"

mkdir -p $PKI_DIR
kubectl config set-cluster kubernetes \
    --server=$KUBERNETES_MASTER \
    --certificate-authority=$PKI_DIR/$ROLE-ca.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-credentials $USER \
    --client-certificate=$PKI_DIR/$ROLE-cert.pem \
    --client-key=$PKI_DIR/$ROLE-key.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-context default \
    --cluster=kubernetes \
    --user=$USER \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config use-context default --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml

exec 2>&1
exec kube-proxy ${KUBE_PROXY_OPTS}
