#!/bin/bash

source /etc/envvars

until curl -s http://localhost:8080; do echo "Waiting for API Server..."; sleep 3; done;

export ROLE=kube-proxy
export USER=system:kube-proxy

KUBE_PROXY_OPTS="\
--hostname-override=$NODE_NAME \
--cluster-cidr "$CLUSTER_CIDR" \
--proxy-mode=ipvs \
--feature-gates=$FEATURE_GATES \
--kubeconfig=/etc/kubernetes/$ROLE-kubeconfig.yml \
--logtostderr=true \
--v=2 \
"

mkdir -p /etc/kubernetes
kubectl config set-cluster kubernetes \
    --server=http://localhost:8080 \
    --kubeconfig=/etc/kubernetes/$ROLE-kubeconfig.yml
kubectl config set-context default \
    --cluster=kubernetes \
    --user=$USER \
    --kubeconfig=/etc/kubernetes/$ROLE-kubeconfig.yml
kubectl config use-context default --kubeconfig=/etc/kubernetes/$ROLE-kubeconfig.yml

exec 2>&1
exec kube-proxy ${KUBE_PROXY_OPTS}
